controllers/SpecificInformationController.php
<?php
/**
 * Created by PhpStorm.
 * User: Maksim
 * Date: 20.12.2017
 * Time: 14:41
 */

namespace app\controllers;

use app\models\GameJudiciarys;
use app\models\GameOtherStatistic;
use app\models\GameProtocolCommands;
use app\models\GameProtocolTeamComparisons;
use app\models\GameRootedStatistics;
use app\models\Games;
use app\models\PersonnelCommissars;
use app\models\PersonnelJudiciarys;
use app\models\PersonnelTrainers;
use app\models\PlayerCareers;
use app\models\PlayerHighs;
use app\models\Players;
use app\models\PlayerToSeason;
use app\models\SearchGameProtocolTeamComparisons;
use app\models\Teams;
use app\models\TrainersToSeasons;
use Yii;
use yii\web\Controller;

class SpecificInformationController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionFirstData()
    {
        return $this->render('first-data');
    }

    public function actionPlayerData()
    {
        return $this->render('player-data');
    }

    public function actionTeamData()
    {
        return $this->render('team-data');
    }

    public function actionGameData()
    {
        return $this->render('game-data');
    }

    public function actionPlayer()
    {
        $id = Yii::$app->request->get('player_id');
        $player = Players::find()->where(['id' => $id])->asArray()->one();
        if(!empty($player))
        {
            $playerCareers = PlayerCareers::find()->where(['player_id' => $id])->with(['season', 'club'])->orderBy(['id' => SORT_DESC])->all();
            $playerHighs = PlayerHighs::find()->where(['player_id' => $id])->with('season')->all();
            $playerToSeason = PlayerToSeason::find()->where(['player_id' => $id])->with(['season', 'club'])->all();
            return $this->render('player', compact('player', 'playerCareers', 'playerHighs', 'playerToSeason'));
        }
        else
        {
            return $this->asJson('Игрок не найден');
        }
    }

    public function actionGame()
    {
        $id = Yii::$app->request->get('game_id');
        $game = Games::find()->where(['id' => $id])->with(['season', 'command1', 'command2', 'commissar'])->all()[0];
        if (!empty($game))
        {
            $gameOtherStatistic = GameOtherStatistic::find()->where(['game_id' => $id])->all();
            $gameProtocolCommands = GameProtocolCommands::find()->where(['game_id' => $id])->with(['player'])->all();
            $gameProtocolTeamComparisons = GameProtocolTeamComparisons::find()->where(['game_id' => $id])->all();
            $gameRootedStatistics = GameRootedStatistics::find()->where(['game_id' => $id])->with(['team'])->all();
            $gameJudiciarys = GameJudiciarys::find()->where(['game_id' => $id])->all();
            return $this->render('game', compact('game', 'gameOtherStatistic', 'gameProtocolCommands', 'gameProtocolTeamComparisons', 'gameRootedStatistics', 'gameJudiciarys'));
        }
        else
        {
            return $this->asJson('Игра не найдена');
        }
    }

    public function actionTeam()
    {
        $id = Yii::$app->request->get('team_id');
        $team = Teams::find()->where(['team_id' => $id])->all();
        if(!empty($team))
        {
            return $this->render('team', compact('team'));
        }
        else
        {
            return $this->asJson('Команда не найдена');
        }
    }
    public function actionTrainer()
    {
        $id = Yii::$app->request->get('trainer_id');
        $personnelTrainers = PersonnelTrainers::find()->where(['id' => $id])->all()[0];
        if(!empty($personnelTrainers))
        {
            $trainersToSeasons = TrainersToSeasons::find()->where(['trainer_id' => $personnelTrainers->id])->all();
            return $this->render('trainer', compact('personnelTrainers','trainersToSeasons'));
        }
        else
        {
            return $this->asJson('Тренер не найден');
        }
    }

    public function actionCommissar()
    {
        $id = Yii::$app->request->get('commissar_id');
        $commissar = PersonnelCommissars::find()->where(['id' => $id])->all()[0];
        if(!empty($commissar))
        {
            $gamesForCommissar = Games::find()->where(['commissar_id' => $id])->all();
            return $this->render('commissar', compact('commissar', 'gamesForCommissar'));
        }
        else
        {
            return $this->asJson('Комисар не найден');
        }
    }

    public function actionJudiciary()
    {
        $id = Yii::$app->request->get('judiciary_id');
        $judiciary = PersonnelJudiciarys::find()->where(['id' => $id])->all()[0];
        if(!empty($judiciary))
        {
            $gamesForJudiciary = GameJudiciarys::find()->where(['judiciary_id' => $id])->all();
            $gameJudiciarys = [];
            foreach($gamesForJudiciary as $key=>$value)
            {

                $gameJudiciarys[$key] = GameJudiciarys::find()->where(['game_id' => $value->game_id])->all();
            }
//            return $this->asJson($gameJudiciarys);
            return $this->render('judiciary', compact('judiciary', 'gamesForJudiciary', 'gameJudiciarys'));
        }
        else
        {
            return $this->asJson('Суддя не найден');
        }
    }
}

views/specific-information/commissar.php
<h2>Информация об комисаре</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">id комисара</th>
        <th scope="col">Имья</th>
        <th scope="col">Фамилия</th>
    </tr>
    </thead>
    <tbody>

    <tr>
        <th scope="row"><?= $commissar->id ?></th>
        <td><?= $commissar->first_name ?></td>
        <td><?= $commissar->last_name ?></td>
    </tr>
    </tbody>
</table>
<br>
<h2>Игры, в которых учасвувал</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">id игры</th>
        <th scope="col">Сезон</th>
        <th scope="col">Дата</th>
        <th scope="col">Номер игры</th>
        <th scope="col">Група</th>
        <th scope="col">Шаг</th>
        <th scope="col">Хазяева</th>
        <th scope="col">Гости</th>
        <th scope="col">Зерультат хозяев</th>
        <th scope="col">Зерультат гостей</th>
        <th scope="col">Зал</th>
        <th scope="col">Комисар</th>
        <th scope="col">Количество зрителей</th>
        <th scope="col">Первая четвердь хозяева</th>
        <th scope="col">Первая четвердь гости</th>
        <th scope="col">Вторая четвердь хозяева</th>
        <th scope="col">Вторая четвердь гости</th>
        <th scope="col">Третья четвердь хозяева</th>
        <th scope="col">Третья четвердь гости</th>
        <th scope="col">Четвёртая четвердь хозяева</th>
        <th scope="col">Четвёртая четвердь гости</th>
        <th scope="col">Результат пьятерки хозяева</th>
        <th scope="col">Результат пьятерки гости</th>
        <th scope="col">Забили запасные хозяева</th>
        <th scope="col">Забили запасные гости</th>
        <th scope="col">Найбольший рывок хозяева</th>
        <th scope="col">Найбольший рывок гости</th>
        <th scope="col">Найбольший розрыв хозяева</th>
        <th scope="col">Найбольший розрыв гости</th>
        <th scope="col">Очки с зоны хозяева</th>
        <th scope="col">Очки с зоны гости</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($gamesForCommissar as $key=>$game): ?>
        <tr>
            <th scope="row"><?= $game->id ?></th>
            <td><?= $game->season->name ?></td>
            <td><?= $game->date ?></td>
            <td><?= $game->number_game ?></td>
            <td><?= $game->group ?></td>
            <td><?= $game->step ?></td>
            <td><?= $game->command1->name ?></td>
            <td><?= $game->command2->name ?></td>
            <td><?= $game->result_command_1 ?></td>
            <td><?= $game->result_command_2 ?></td>
            <td><?= $game->arena ?></td>
            <td><?= $game->commissar->first_name.' '.$game->commissar->last_name ?></td>
            <td><?= $game->viewers ?></td>
            <td><?= $game->first_quarter_comand_1 ?></td>
            <td><?= $game->first_quarter_comand_2 ?></td>
            <td><?= $game->second_quarter_comand_1 ?></td>
            <td><?= $game->second_quarter_comand_2 ?></td>
            <td><?= $game->third_quarter_comand_1 ?></td>
            <td><?= $game->third_quarter_comand_2 ?></td>
            <td><?= $game->fourth_quarter_comand_1 ?></td>
            <td><?= $game->fourth_quarter_comand_2 ?></td>
            <td><?= $game->the_result_of_the_five_comand_1 ?></td>
            <td><?= $game->the_result_of_the_five_comand_2 ?></td>
            <td><?= $game->beat_the_spare_comand_1 ?></td>
            <td><?= $game->beat_the_spare_comand_2 ?></td>
            <td><?= $game->the_hottest_jerk_comand_1 ?></td>
            <td><?= $game->the_hottest_jerk_comand_2 ?></td>
            <td><?= $game->the_biggest_gap_comand_1 ?></td>
            <td><?= $game->the_biggest_gap_comand_2 ?></td>
            <td><?= $game->points_from_the_zone_comand_1 ?></td>
            <td><?= $game->points_from_the_zone_comand_2 ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

views/specific-information/first-data.php
<?php
use yii\helpers\Html;
?>
<h2>Первоначальные данные</h2>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Лигы", ['/league/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Сезоны", ['/season/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Персонал", ['/personnel/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>

views/specific-information/game-data.php
<?php
use yii\helpers\Html;
?>
<h2>Все информация об играх</h2>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Все игры", ['/game/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Дополнительная статистика по играх", ['/game-other-statistic/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Протокол по играх", ['/game-protocol-commands/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Протокол команд по играх", ['/game-protocol-team-comparisons/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Сравнительная статистика по играх", ['/game-rooted-statistics/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>

views/specific-information/game.php
<?php if(!empty($game)): ?>
    <h2>Общее инфо</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">id игры</th>
            <th scope="col">Сезон</th>
            <th scope="col">Дата</th>
            <th scope="col">Номер игры</th>
            <th scope="col">Група</th>
            <th scope="col">Шаг</th>
            <th scope="col">Хазяева</th>
            <th scope="col">Гости</th>
            <th scope="col">Зерультат хозяев</th>
            <th scope="col">Зерультат гостей</th>
            <th scope="col">Зал</th>
            <th scope="col">Комисар</th>
            <th scope="col">Количество зрителей</th>
            <th scope="col">Первая четвердь хозяева</th>
            <th scope="col">Первая четвердь гости</th>
            <th scope="col">Вторая четвердь хозяева</th>
            <th scope="col">Вторая четвердь гости</th>
            <th scope="col">Третья четвердь хозяева</th>
            <th scope="col">Третья четвердь гости</th>
            <th scope="col">Четвёртая четвердь хозяева</th>
            <th scope="col">Четвёртая четвердь гости</th>
            <th scope="col">Результат пьятерки хозяева</th>
            <th scope="col">Результат пьятерки гости</th>
            <th scope="col">Забили запасные хозяева</th>
            <th scope="col">Забили запасные гости</th>
            <th scope="col">Найбольший рывок хозяева</th>
            <th scope="col">Найбольший рывок гости</th>
            <th scope="col">Найбольший розрыв хозяева</th>
            <th scope="col">Найбольший розрыв гости</th>
            <th scope="col">Очки с зоны хозяева</th>
            <th scope="col">Очки с зоны гости</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row"><?= $game->id ?></th>
            <td><?= $game->season->name ?></td>
            <td><?= $game->date ?></td>
            <td><?= $game->number_game ?></td>
            <td><?= $game->group ?></td>
            <td><?= $game->step ?></td>
            <td><?= $game->command1->name ?></td>
            <td><?= $game->command2->name ?></td>
            <td><?= $game->result_command_1 ?></td>
            <td><?= $game->result_command_2 ?></td>
            <td><?= $game->arena ?></td>
            <td><?= $game->commissar->first_name.' '.$game->commissar->last_name ?></td>
            <td><?= $game->viewers ?></td>
            <td><?= $game->first_quarter_comand_1 ?></td>
            <td><?= $game->first_quarter_comand_2 ?></td>
            <td><?= $game->second_quarter_comand_1 ?></td>
            <td><?= $game->second_quarter_comand_2 ?></td>
            <td><?= $game->third_quarter_comand_1 ?></td>
            <td><?= $game->third_quarter_comand_2 ?></td>
            <td><?= $game->fourth_quarter_comand_1 ?></td>
            <td><?= $game->fourth_quarter_comand_2 ?></td>
            <td><?= $game->the_result_of_the_five_comand_1 ?></td>
            <td><?= $game->the_result_of_the_five_comand_2 ?></td>
            <td><?= $game->beat_the_spare_comand_1 ?></td>
            <td><?= $game->beat_the_spare_comand_2 ?></td>
            <td><?= $game->the_hottest_jerk_comand_1 ?></td>
            <td><?= $game->the_hottest_jerk_comand_2 ?></td>
            <td><?= $game->the_biggest_gap_comand_1 ?></td>
            <td><?= $game->the_biggest_gap_comand_2 ?></td>
            <td><?= $game->points_from_the_zone_comand_1 ?></td>
            <td><?= $game->points_from_the_zone_comand_2 ?></td>
        </tr>
        </tbody>
    </table>
    <h2>Протокол по игре</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Комана</th>
            <th scope="col">Игрок</th>
            <th scope="col">Номер игрока</th>
            <th scope="col">Время в игре</th>
            <th scope="col">Двухочковых бросков</th>
            <th scope="col">Двухочковых бросков/попал</th>
            <th scope="col">Двухочковых бросков/процент</th>
            <th scope="col">Трехочковых бросков</th>
            <th scope="col">Трехочковых бросков/попал</th>
            <th scope="col">Трехочковых бросков/процент</th>
            <th scope="col">Попыток в атаке</th>
            <th scope="col">Попыток в защите</th>
            <th scope="col">Попыток процент</th>
            <th scope="col">Штрафных бросков</th>
            <th scope="col">Штрафных бросков/попал</th>
            <th scope="col">Штрафных бросков/процент</th>
            <th scope="col">Подборов в атаке</th>
            <th scope="col">Подборов в нападении</th>
            <th scope="col">Подборов все</th>
            <th scope="col">Передачи</th>
            <th scope="col">Персональные фолы</th>
            <th scope="col">Потери</th>
            <th scope="col">Перехваты</th>
            <th scope="col">Блок-шот 1</th>
            <th scope="col">Блок-шот 2</th>
            <th scope="col">Эфэктивность</th>
            <th scope="col">+/-</th>
            <th scope="col">Полученые очки</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($gameProtocolCommands as $key=> $item): ?>
        <tr>
            <th scope="row"><?= $key+1 ?></th>
            <td><?= ($item->team_status == 1) ? $game->command1->name : $game->command2->name ?></td>
            <td><?= $item->player->first_name.' '.$item->player->last_name ?></td>
            <td><?= $item->player_number ?></td>
            <td><?= $item->time_in_game ?></td>
            <td><?= $item->two_point_kiddies ?></td>
            <td><?= $item->two_point_kiddies_ok ?></td>
            <td><?= $item->two_point_kiddies_percent ?></td>
            <td><?= $item->three_point_kiddies ?></td>
            <td><?= $item->three_point_kiddies_ok ?></td>
            <td><?= $item->three_point_kiddies_percent ?></td>
            <td><?= $item->for_game_attempt ?></td>
            <td><?= $item->for_game_attempt_ok ?></td>
            <td><?= $item->for_game_attempt_percent ?></td>
            <td><?= $item->one_point_kiddies ?></td>
            <td><?= $item->one_point_kiddies_ok ?></td>
            <td><?= $item->one_point_kiddies_percent ?></td>
            <td><?= $item->picking_up_in_an_attack ?></td>
            <td><?= $item->picking_up_in_defense ?></td>
            <td><?= $item->overall_picking_up ?></td>
            <td><?= $item->transmissions ?></td>
            <td><?= $item->personal_foul ?></td>
            <td><?= $item->losses ?></td>
            <td><?= $item->interception ?></td>
            <td><?= $item->block_shots_1 ?></td>
            <td><?= $item->block_shots_2 ?></td>
            <td><?= $item->efficiency ?></td>
            <td><?= $item->plus_minus ?></td>
            <td><?= $item->gained_points ?></td>
            <?php endforeach; ?>
        </tbody>
    </table>
    <h2>Сравнение команд</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Комана</th>
            <th scope="col">Двухочковых бросков</th>
            <th scope="col">Двухочковых бросков/попал</th>
            <th scope="col">Двухочковых бросков/процент</th>
            <th scope="col">Трехочковых бросков</th>
            <th scope="col">Трехочковых бросков/попал</th>
            <th scope="col">Трехочковых бросков/процент</th>
            <th scope="col">Штрафных бросков</th>
            <th scope="col">Штрафных бросков/попал</th>
            <th scope="col">Штрафных бросков/процент</th>
            <th scope="col">Подборов в атаке</th>
            <th scope="col">Подборов в нападении</th>
            <th scope="col">Подборов все</th>
            <th scope="col">Передачи</th>
            <th scope="col">Персональные фолы</th>
            <th scope="col">Потери</th>
            <th scope="col">Перехваты</th>
            <th scope="col">Блок-шот 1</th>
            <th scope="col">Эфэктивность</th>
            <th scope="col">Полученые очки</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($gameProtocolTeamComparisons as $item): ?>
                <tr>
                    <th scope="row"><?= ($item->team_status == 1) ? $game->command1->name : $game->command2->name ?></th>
                    <td><?= $item->two_point_kiddies ?></td>
                    <td><?= $item->two_point_kiddies_ok ?></td>
                    <td><?= $item->two_point_kiddies_percent ?></td>
                    <td><?= $item->three_point_kiddies ?></td>
                    <td><?= $item->three_point_kiddies_ok ?></td>
                    <td><?= $item->three_point_kiddies_percent ?></td>
                    <td><?= $item->one_point_kiddies ?></td>
                    <td><?= $item->one_point_kiddies_ok ?></td>
                    <td><?= $item->one_point_kiddies_percent ?></td>
                    <td><?= $item->picking_up_in_an_attack ?></td>
                    <td><?= $item->picking_up_in_defense ?></td>
                    <td><?= $item->overall_picking_up ?></td>
                    <td><?= $item->transmissions ?></td>
                    <td><?= $item->personal_foul ?></td>
                    <td><?= $item->losses ?></td>
                    <td><?= $item->interception ?></td>
                    <td><?= $item->block_shots_1 ?></td>
                    <td><?= $item->efficiency ?></td>
                    <td><?= $item->gained_points ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <h2>Сравнение старт/лава</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Команда</th>
            <th scope="col">Статус</th>
            <th scope="col">Время в игре</th>
            <th scope="col">Двухочковых бросков</th>
            <th scope="col">Двухочковых бросков/попал</th>
            <th scope="col">Трехочковых бросков</th>
            <th scope="col">Трехочковых бросков/попал</th>
            <th scope="col">Штрафных бросков</th>
            <th scope="col">Штрафных бросков/попал</th>
            <th scope="col">Подборов в атаке</th>
            <th scope="col">Подборов в нападении</th>
            <th scope="col">Подборов все</th>
            <th scope="col">Передачи</th>
            <th scope="col">Персональные фолы</th>
            <th scope="col">Потери</th>
            <th scope="col">Перехваты</th>
            <th scope="col">Блок-шот</th>
            <th scope="col">Эфэктивность</th>
            <th scope="col">Полученые очки</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($gameRootedStatistics as $item): ?>
                <tr>
                    <th scope="row"><?= $item->team->name ?></th>
                    <td><?= $item->team_status ?></td>
                    <td><?= $item->time_in_game ?></td>
                    <td><?= $item->two_point_kiddies ?></td>
                    <td><?= $item->two_point_kiddies_ok ?></td>
                    <td><?= $item->three_point_kiddies ?></td>
                    <td><?= $item->three_point_kiddies_ok ?></td>
                    <td><?= $item->one_point_kiddies ?></td>
                    <td><?= $item->one_point_kiddies_ok ?></td>
                    <td><?= $item->picking_up_in_an_attack ?></td>
                    <td><?= $item->picking_up_in_defense ?></td>
                    <td><?= $item->overall_picking_up ?></td>
                    <td><?= $item->transmissions ?></td>
                    <td><?= $item->personal_foul ?></td>
                    <td><?= $item->losses ?></td>
                    <td><?= $item->interception ?></td>
                    <td><?= $item->block_shots ?></td>
                    <td><?= $item->efficiency ?></td>
                    <td><?= $item->gained_points ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <h2>Другая статистика</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Хозяева</th>
            <th scope="col">Гости</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($gameOtherStatistic as $item): ?>
                <tr>
                    <th scope="row"><?= $item->name ?></th>
                    <td><?= $item->team_1 ?></td>
                    <td><?= $item->team_2 ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <h2>Судди</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
        </tr>
        </thead>
        <tbody>
        <?php if(empty($gameJudiciarys)): ?>
            <tr>
                <th scope="row"><h2>Суддей не найдено</h2></th>
            </tr>
        <?php else: ?>
            <?php foreach($gameJudiciarys as $keyGameJudiciarys => $valueGameJudiciarys): ?>
                <tr>
                    <th scope="row"><?= $keyGameJudiciarys ?></th>
                    <td><?= $valueGameJudiciarys->judiciary->first_name ?></td>
                    <td><?= $valueGameJudiciarys->judiciary->last_name ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
<?php endif; ?>

views/specific-information/index.php
<?php
use yii\helpers\Html;
?>

<div class="row">
    <?= Html::beginForm(['/specific-information/player'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "player_id", "", ['class' => ["form-control"], 'placeholder' => 'id игрока']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть игрока", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>
<div class="row">
    <?= Html::beginForm(['/specific-information/game'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "game_id", "", ['class' => ["form-control"], 'placeholder' => 'id игры']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть игру", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>
<div class="row">
    <?= Html::beginForm(['/specific-information/team'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "team_id", "", ['class' => ["form-control"], 'placeholder' => 'id команды']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть команду", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>
<div class="row">
    <?= Html::beginForm(['/specific-information/trainer'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "trainer_id", "", ['class' => ["form-control"], 'placeholder' => 'id тренера']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть тренера", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>
<div class="row">
    <?= Html::beginForm(['/specific-information/commissar'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "commissar_id", "", ['class' => ["form-control"], 'placeholder' => 'id комисара']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть комисара", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>
<div class="row">
    <?= Html::beginForm(['/specific-information/judiciary'], 'get') ?>
        <div class="col-md-6">
            <?= Html::input("text", "judiciary_id", "", ['class' => ["form-control"], 'placeholder' => 'id арбитра']) ?>
        </div>
        <div class="col-md-6">
            <?= Html::submitButton("Посмотреть арбитра", ['class' => ["btn", "btn-success"]]) ?>
        </div>
    <?= Html::endForm() ?>
</div>
<br>

views/specific-information/player-data.php
<?php
use yii\helpers\Html;
?>
<h2>Все информация об игроках</h2>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Все игроки", ['/player/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Карьера игроков", ['/player-career/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Сезоны игроков", ['/player-season/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12">
        <?= Html::a("Рекорды игроков", ['/player-highs/index'], ['class' => ["btn", "btn-success"]]) ?>
    </div>
</div>